services:
  web:
    build: .
    # command: gunicorn ptmx_backend.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ptmx_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
