# Generated by Django 5.0.4 on 2024-06-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Associate this message with a specific user.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
